# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.channels_api import ChannelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_channel_get(self):
        """Test case for api_v2_channel_get

        List Channels  # noqa: E501
        """
        pass

    def test_api_v2_channel_payment_get(self):
        """Test case for api_v2_channel_payment_get

        List Channel Payments  # noqa: E501
        """
        pass

    def test_api_v2_channel_payment_uuid_get(self):
        """Test case for api_v2_channel_payment_uuid_get

        Get Channel Payment  # noqa: E501
        """
        pass

    def test_api_v2_channel_post(self):
        """Test case for api_v2_channel_post

        Create Channel  # noqa: E501
        """
        pass

    def test_api_v2_channel_uuid_get(self):
        """Test case for api_v2_channel_uuid_get

        Get Channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
