# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.trading_and_conversions_api import TradingAndConversionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTradingAndConversionsApi(unittest.TestCase):
    """TradingAndConversionsApi unit test stubs"""

    def setUp(self):
        self.api = TradingAndConversionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_quote_accept(self):
        """Test case for quote_accept

        Accept Quote  # noqa: E501
        """
        pass

    def test_quote_create(self):
        """Test case for quote_create

        Create Quote  # noqa: E501
        """
        pass

    def test_quote_list(self):
        """Test case for quote_list

        List Quotes  # noqa: E501
        """
        pass

    def test_quote_read(self):
        """Test case for quote_read

        Read Quote  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
