# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transaction_report_request_data import TransactionReportRequestData  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionReportRequestData(unittest.TestCase):
    """TransactionReportRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionReportRequestData(self):
        """Test TransactionReportRequestData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transaction_report_request_data.TransactionReportRequestData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
