# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.merchant_ids_api import MerchantIDsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMerchantIDsApi(unittest.TestCase):
    """MerchantIDsApi unit test stubs"""

    def setUp(self):
        self.api = MerchantIDsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_merchant_id_create(self):
        """Test case for merchant_id_create

        Create Merchant ID  # noqa: E501
        """
        pass

    def test_merchant_id_list(self):
        """Test case for merchant_id_list

        List Merchant IDs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
