# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wallets_api import WalletsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletsApi(unittest.TestCase):
    """WalletsApi unit test stubs"""

    def setUp(self):
        self.api = WalletsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transaction_report(self):
        """Test case for transaction_report

        Transactions Report  # noqa: E501
        """
        pass

    def test_wallet_balance_list(self):
        """Test case for wallet_balance_list

        List Wallet Balances  # noqa: E501
        """
        pass

    def test_wallet_create(self):
        """Test case for wallet_create

        Create Wallet  # noqa: E501
        """
        pass

    def test_wallet_list(self):
        """Test case for wallet_list

        List Wallets  # noqa: E501
        """
        pass

    def test_wallet_r_get(self):
        """Test case for wallet_r_get

        Get Wallet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
