# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AcceptedQuote(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote': 'Quote',
        'pay_in_instruction': 'PayInInstruction'
    }

    attribute_map = {
        'quote': 'quote',
        'pay_in_instruction': 'payInInstruction'
    }

    def __init__(self, quote=None, pay_in_instruction=None):  # noqa: E501
        """AcceptedQuote - a model defined in Swagger"""  # noqa: E501
        self._quote = None
        self._pay_in_instruction = None
        self.discriminator = None
        if quote is not None:
            self.quote = quote
        if pay_in_instruction is not None:
            self.pay_in_instruction = pay_in_instruction

    @property
    def quote(self):
        """Gets the quote of this AcceptedQuote.  # noqa: E501


        :return: The quote of this AcceptedQuote.  # noqa: E501
        :rtype: Quote
        """
        return self._quote

    @quote.setter
    def quote(self, quote):
        """Sets the quote of this AcceptedQuote.


        :param quote: The quote of this AcceptedQuote.  # noqa: E501
        :type: Quote
        """

        self._quote = quote

    @property
    def pay_in_instruction(self):
        """Gets the pay_in_instruction of this AcceptedQuote.  # noqa: E501


        :return: The pay_in_instruction of this AcceptedQuote.  # noqa: E501
        :rtype: PayInInstruction
        """
        return self._pay_in_instruction

    @pay_in_instruction.setter
    def pay_in_instruction(self, pay_in_instruction):
        """Sets the pay_in_instruction of this AcceptedQuote.


        :param pay_in_instruction: The pay_in_instruction of this AcceptedQuote.  # noqa: E501
        :type: PayInInstruction
        """

        self._pay_in_instruction = pay_in_instruction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AcceptedQuote, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AcceptedQuote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
