# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Fee(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service': 'float',
        'processing': 'float'
    }

    attribute_map = {
        'service': 'service',
        'processing': 'processing'
    }

    def __init__(self, service=None, processing=None):  # noqa: E501
        """Fee - a model defined in Swagger"""  # noqa: E501
        self._service = None
        self._processing = None
        self.discriminator = None
        if service is not None:
            self.service = service
        if processing is not None:
            self.processing = processing

    @property
    def service(self):
        """Gets the service of this Fee.  # noqa: E501


        :return: The service of this Fee.  # noqa: E501
        :rtype: float
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this Fee.


        :param service: The service of this Fee.  # noqa: E501
        :type: float
        """

        self._service = service

    @property
    def processing(self):
        """Gets the processing of this Fee.  # noqa: E501


        :return: The processing of this Fee.  # noqa: E501
        :rtype: float
        """
        return self._processing

    @processing.setter
    def processing(self, processing):
        """Sets the processing of this Fee.


        :param processing: The processing of this Fee.  # noqa: E501
        :type: float
        """

        self._processing = processing

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Fee, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Fee):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
