# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PayOutMethod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'code': 'str',
        'currency': 'str',
        'account_methods': 'list[AccountMethod]'
    }

    attribute_map = {
        'id': 'id',
        'code': 'code',
        'currency': 'currency',
        'account_methods': 'accountMethods'
    }

    def __init__(self, id=None, code=None, currency=None, account_methods=None):  # noqa: E501
        """PayOutMethod - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._code = None
        self._currency = None
        self._account_methods = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if code is not None:
            self.code = code
        if currency is not None:
            self.currency = currency
        if account_methods is not None:
            self.account_methods = account_methods

    @property
    def id(self):
        """Gets the id of this PayOutMethod.  # noqa: E501


        :return: The id of this PayOutMethod.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PayOutMethod.


        :param id: The id of this PayOutMethod.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def code(self):
        """Gets the code of this PayOutMethod.  # noqa: E501


        :return: The code of this PayOutMethod.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this PayOutMethod.


        :param code: The code of this PayOutMethod.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def currency(self):
        """Gets the currency of this PayOutMethod.  # noqa: E501


        :return: The currency of this PayOutMethod.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this PayOutMethod.


        :param currency: The currency of this PayOutMethod.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def account_methods(self):
        """Gets the account_methods of this PayOutMethod.  # noqa: E501


        :return: The account_methods of this PayOutMethod.  # noqa: E501
        :rtype: list[AccountMethod]
        """
        return self._account_methods

    @account_methods.setter
    def account_methods(self, account_methods):
        """Sets the account_methods of this PayOutMethod.


        :param account_methods: The account_methods of this PayOutMethod.  # noqa: E501
        :type: list[AccountMethod]
        """

        self._account_methods = account_methods

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PayOutMethod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PayOutMethod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
