# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.merchant_channel import MerchantChannel
from openapi_client import configuration


class TestMerchantChannel(unittest.TestCase):
    """MerchantChannel unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
