# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class MerchantChannelRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "reference",
            "merchantId",
            "payCurrency",
            "displayCurrency",
        }
        
        class properties:
            merchantId = schemas.StrSchema
            payCurrency = schemas.StrSchema
            displayCurrency = schemas.StrSchema
            reference = schemas.StrSchema
            __annotations__ = {
                "merchantId": merchantId,
                "payCurrency": payCurrency,
                "displayCurrency": displayCurrency,
                "reference": reference,
            }
    
    reference: MetaOapg.properties.reference
    merchantId: MetaOapg.properties.merchantId
    payCurrency: MetaOapg.properties.payCurrency
    displayCurrency: MetaOapg.properties.displayCurrency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantId"]) -> MetaOapg.properties.merchantId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payCurrency"]) -> MetaOapg.properties.payCurrency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displayCurrency"]) -> MetaOapg.properties.displayCurrency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reference"]) -> MetaOapg.properties.reference: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["merchantId", "payCurrency", "displayCurrency", "reference", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantId"]) -> MetaOapg.properties.merchantId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payCurrency"]) -> MetaOapg.properties.payCurrency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displayCurrency"]) -> MetaOapg.properties.displayCurrency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reference"]) -> MetaOapg.properties.reference: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["merchantId", "payCurrency", "displayCurrency", "reference", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        reference: typing.Union[MetaOapg.properties.reference, str, ],
        merchantId: typing.Union[MetaOapg.properties.merchantId, str, ],
        payCurrency: typing.Union[MetaOapg.properties.payCurrency, str, ],
        displayCurrency: typing.Union[MetaOapg.properties.displayCurrency, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MerchantChannelRequest':
        return super().__new__(
            cls,
            *_args,
            reference=reference,
            merchantId=merchantId,
            payCurrency=payCurrency,
            displayCurrency=displayCurrency,
            _configuration=_configuration,
            **kwargs,
        )
