# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class PaymentStatusDto(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Payment status
    """


    class MetaOapg:
        enum_value_to_name = {
            "PENDING": "PENDING",
            "PROCESSING": "PROCESSING",
            "CANCELLED": "CANCELLED",
            "COMPLETE": "COMPLETE",
            "UNDERPAID": "UNDERPAID",
            "OVERPAID": "OVERPAID",
            "EXPIRED": "EXPIRED",
        }
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("PENDING")
    
    @schemas.classproperty
    def PROCESSING(cls):
        return cls("PROCESSING")
    
    @schemas.classproperty
    def CANCELLED(cls):
        return cls("CANCELLED")
    
    @schemas.classproperty
    def COMPLETE(cls):
        return cls("COMPLETE")
    
    @schemas.classproperty
    def UNDERPAID(cls):
        return cls("UNDERPAID")
    
    @schemas.classproperty
    def OVERPAID(cls):
        return cls("OVERPAID")
    
    @schemas.classproperty
    def EXPIRED(cls):
        return cls("EXPIRED")
