# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TradingAndConversionsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def quote_accept(self, uuid, **kwargs):  # noqa: E501
        """Accept Quote  # noqa: E501

        Executes a quote.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_accept(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: The quote UUID you are accepting. (required)
        :return: AcceptedQuote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.quote_accept_with_http_info(uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.quote_accept_with_http_info(uuid, **kwargs)  # noqa: E501
            return data

    def quote_accept_with_http_info(self, uuid, **kwargs):  # noqa: E501
        """Accept Quote  # noqa: E501

        Executes a quote.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_accept_with_http_info(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: The quote UUID you are accepting. (required)
        :return: AcceptedQuote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method quote_accept" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'uuid' is set
        if ('uuid' not in params or
                params['uuid'] is None):
            raise ValueError("Missing the required parameter `uuid` when calling `quote_accept`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'uuid' in params:
            path_params['uuid'] = params['uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Hawk']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/quote/accept/{uuid}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AcceptedQuote',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def quote_create(self, **kwargs):  # noqa: E501
        """Create Quote  # noqa: E501

        Creates a quote to convert between wallets.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_create(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuoteRequest body:
        :param bool estimate: Create estimate quote
        :return: Quote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.quote_create_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.quote_create_with_http_info(**kwargs)  # noqa: E501
            return data

    def quote_create_with_http_info(self, **kwargs):  # noqa: E501
        """Create Quote  # noqa: E501

        Creates a quote to convert between wallets.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_create_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param QuoteRequest body:
        :param bool estimate: Create estimate quote
        :return: Quote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'estimate']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method quote_create" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'estimate' in params:
            query_params.append(('estimate', params['estimate']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Hawk']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/quote', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Quote',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def quote_list(self, merchant_id, **kwargs):  # noqa: E501
        """List Quotes  # noqa: E501

        Retrieves all quotes on a specific Merchant ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_list(merchant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str merchant_id: Merchant ID you are retrieving quotes from. (required)
        :return: list[Quote]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.quote_list_with_http_info(merchant_id, **kwargs)  # noqa: E501
        else:
            (data) = self.quote_list_with_http_info(merchant_id, **kwargs)  # noqa: E501
            return data

    def quote_list_with_http_info(self, merchant_id, **kwargs):  # noqa: E501
        """List Quotes  # noqa: E501

        Retrieves all quotes on a specific Merchant ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_list_with_http_info(merchant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str merchant_id: Merchant ID you are retrieving quotes from. (required)
        :return: list[Quote]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['merchant_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method quote_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'merchant_id' is set
        if ('merchant_id' not in params or
                params['merchant_id'] is None):
            raise ValueError("Missing the required parameter `merchant_id` when calling `quote_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'merchant_id' in params:
            path_params['merchantId'] = params['merchant_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Hawk']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/quote/{merchantId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Quote]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def quote_read(self, uuid, **kwargs):  # noqa: E501
        """Read Quote  # noqa: E501

        Retrieves a specific quote.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_read(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: UUID of the quote you are retrieving. (required)
        :return: Quote
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.quote_read_with_http_info(uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.quote_read_with_http_info(uuid, **kwargs)  # noqa: E501
            return data

    def quote_read_with_http_info(self, uuid, **kwargs):  # noqa: E501
        """Read Quote  # noqa: E501

        Retrieves a specific quote.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.quote_read_with_http_info(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: UUID of the quote you are retrieving. (required)
        :return: Quote
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method quote_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'uuid' is set
        if ('uuid' not in params or
                params['uuid'] is None):
            raise ValueError("Missing the required parameter `uuid` when calling `quote_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'uuid' in params:
            path_params['uuid'] = params['uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Hawk']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/quote/{uuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Quote',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
