# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_currency_crypto.get import ListCurrenciesCrypto
from openapi_client.paths.api_currency_deposit.get import ListCurrenciesDeposit
from openapi_client.paths.api_currency_fiat.get import ListCurrenciesFiat


class CurrenciesApi(
    ListCurrenciesCrypto,
    ListCurrenciesDeposit,
    ListCurrenciesFiat,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
