# coding: utf-8

"""
    BVNK API Endpoints

    The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_transaction_report.get import TransactionReport
from openapi_client.paths.api_wallet_balances.get import WalletBalanceList
from openapi_client.paths.api_wallet.post import WalletCreate
from openapi_client.paths.api_wallet.get import WalletList
from openapi_client.paths.api_wallet_id.get import WalletRGet


class WalletsApi(
    TransactionReport,
    WalletBalanceList,
    WalletCreate,
    WalletList,
    WalletRGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
